#!/bin/bash

# script to be run to compile java source file(s) & make a jar with it;
# compiled classes to be placed inside ./bin/

if [ ! -d "./bin/" ]; then
	mkdir bin
fi

find . -name "*.java" | xargs javac -d bin/

# this jar can be used as library in any other java project; check documentation


if [ ! -d "./release/" ]; then
	mkdir release
fi

jar cvf ./release/in.itzmeanjan.filterit.jar -C bin/ .
rm ./bin -r
